# Generated by Django 4.2 on 2026-02-24 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_bmi', models.FloatField(verbose_name='最小 BMI 值')),
                ('max_bmi', models.FloatField(verbose_name='最大 BMI 值')),
                ('recommendation', models.TextField(verbose_name='运动推荐方案')),
            ],
            options={
                'verbose_name': 'BMI运动推荐',
                'verbose_name_plural': 'BMI运动推荐',
            },
        ),
        migrations.CreateModel(
            name='Inspiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlock_days', models.IntegerField(unique=True, verbose_name='解锁天数')),
                ('content', models.TextField(verbose_name='励志语录')),
            ],
            options={
                'verbose_name': '励志语录',
                'verbose_name_plural': '励志语录',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatars/default.png', upload_to='avatars/', verbose_name='头像')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=1, verbose_name='性别')),
                ('height', models.FloatField(verbose_name='身高(cm)')),
                ('initial_weight', models.FloatField(verbose_name='初始体重(kg)')),
                ('target_weight', models.FloatField(verbose_name='目标体重(kg)')),
                ('streak_count', models.IntegerField(default=0, verbose_name='连续打卡天数')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='打卡日期')),
                ('weight', models.FloatField(verbose_name='当日体重(kg)')),
                ('calories_in', models.IntegerField(default=0, verbose_name='摄入热量(kcal)')),
                ('calories_out', models.IntegerField(default=0, verbose_name='消耗热量(kcal)')),
                ('summary', models.TextField(blank=True, verbose_name='减肥小结')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '打卡记录',
                'verbose_name_plural': '打卡记录',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
